#%RAML 1.0 NamedExample
{
  total: 200,
  customers: [
    {customer-id: "AXN12345",
    name: "Rick John",
    phone: "6457892123",
    e-mail: "rick.john@driscolls.com"},
    {customer-id: "AXN12346",
    name: "Mike Tyson ",
    phone: "6457892000",
    e-mail: "mike.tyson@driscolls.com"},
    {customer-id: "AXN12347",
      name: "Jack Sparrow",
      phone: "6457892987",
      e-mail: "jack.sparrow.john@driscolls.com"},
    {customer-id: "AXN12348",
      name: "Matt Cobra",
      phone: "6457892999",
      e-mail: "matt.cobra@driscolls.com"}
  ]
  }